CREATE TABLE Files (
id INTEGER PRIMARY KEY,
name VARCHAR NOT NULL,
data BLOB,
created DATETIME NOT NULL,
updated DATETIME NOT NULL,
parent INTEGER NOT NULL
);

CREATE TABLE Permissions (
perm_id INTEGER PRIMARY KEY,
user_id INTEGER NOT NULL,
file_id INTEGER NOT NULL,
r_perm BOOLEAN NOT NULL,
w_perm BOOLEAN NOT NULL,
a_perm BOOLEAN NOT NULL,
FOREIGN KEY (file_id) REFERENCES Files(id)
);